Linear Search in Go language
4N1Z/Sorting-Searching-Algorithms pull request #114
Opened 2022-10-13 08:32 UTC by sharmadaisy

2022-10-14 14:14 UTC, AnirudhDaya requested changes
Hey pal, the code works great. But needs documentation like 
-- Explanation on what linear is
-- Complexities

2022-10-15 05:07 UTC, 4N1Z approved these changes

2022-10-16 15:04 UTC, 4N1Z commented
@AnirudhDaya Review the code.

2022-10-19 15:00 UTC, AnirudhDaya submitted a review, later dismissed
Hey pal remove the linear search file as it is empty

2022-10-23 12:34 UTC, 4N1Z approved these changes

2022-10-23 12:34 UTC, merged