Create in_C++.cpp
4N1Z/Sorting-Searching-Algorithms pull request #27
Opened 2022-10-02 02:53 UTC by bishtanuj

I have added a quick sort program written in C++. If you find it correct for your repository than kindly add hacktoberfest-accepted and hacktoberfest2022 label with it.

2022-10-03 16:32 UTC, bishtanuj commented
Didn't get any update...

2022-10-03 17:14 UTC, 4N1Z requested changes
Hey Pal,
Glad to see your contribution 😄
Points to change :

- Add the details of Quick sort as documentation inside the code itself.
- The details should include :
--  What is Quick sort? (or How it works)
-- Time and space complexity.

Happy Coding !

2022-10-03 17:50 UTC, bishtanuj commented
> Hey Pal, Glad to see your contribution 😄 Points to change :
> 
>     * Add the details of Quick sort as documentation inside the code itself.
> 
>     * The details should include :
>       --  What is Quick sort? (or How it works)
>       -- Time and space complexity.
> 
> 
> Happy Coding !

DONE 👍

2022-10-06 18:32 UTC, 4N1Z approved these changes

2022-10-06 18:33 UTC, merged