Added bubble sort in javascript
4N1Z/Sorting-Searching-Algorithms pull request #33
Opened 2022-10-02 13:25 UTC by rahmat-st

2022-10-03 11:07 UTC, rahmat-st commented
can u review my PR please?

2022-10-03 17:06 UTC, AnirudhDaya requested changes
Hey pal, the code works great. But needs documentation like 
-- Explanation on what bubble sort is
-- Complexities

2022-10-03 18:04 UTC, rahmat-st commented
Done

2022-10-06 18:43 UTC, 4N1Z approved these changes

2022-10-06 18:43 UTC, merged