added Searching algorithms:
4N1Z/Sorting-Searching-Algorithms pull request #79
Opened 2022-10-11 08:05 UTC by bhavya-sharma26

I have added BFS / DFS in C++ language in the folder named Searching. Further added the code of BFS in BFS named folder and same for DFS. And the name of the file is as specified by you in contributing.md .
(Name of the folder/folder/file - Searching/BFS/in_C++.cpp and Searching/DFS/in_C++.cpp)

Also I have included a HTML/JAVASCRIPT language code for Linear Search in Searching/Linear-Search named in_ html.html

Please merge my pull request

2022-10-12 14:54 UTC, 4N1Z approved these changes

2022-10-12 14:55 UTC, 4N1Z requested changes
Hey Pal,
Glad to see your contribution and really great code😄
Points to change :

- Add documentation as comments inside the code itself.
- The documentation should include :
--Time and space complexity

Happy Coding !

2022-10-12 16:33 UTC, bhavya-sharma26 commented
I have done the changes requested by you .Please confirm it . 
Or if further changes are required please tell.

2022-10-14 15:01 UTC, AnirudhDaya commented
Sorry buddy, code already exists

2022-10-14 15:01 UTC, closed without merging